version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: bettysami/s5annie-revive-rabbitmq:1.0.0
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: rabbitmq123  # Replace with a secure password
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:   
      - revive
    restart: always

  orders-db:
    container_name: orders-db
    image: bettysami/s5annie-revive-orders-db:latest
    environment:
      MARIADB_ROOT_PASSWORD: orders-db123  # Replace with a secure password
      MARIADB_DATABASE: orders
      MARIADB_USER: orders_user
      MARIADB_PASSWORD: orders1234  # Replace with a secure password
    expose:
      - 3306
    ports:
      - 3307:3306
    volumes:
      - orders-db:/var/lib/mysql
    networks:   
      - revive
    restart: always
    depends_on:
      - rabbitmq

  orders:
    container_name: orders
    image: bettysami/s5annie-revive-orders:latest
    environment:
      DB_HOST: orders-db
      DB_USER: orders_user
      DB_PASSWORD: orders1234  # Should match MARIADB_PASSWORD in orders-db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: rabbitmq123  # Should match RABBITMQ_DEFAULT_PASS in rabbitmq
    expose: 
      - 8080
    ports:
      - 8081:8080
    networks:   
      - revive
    restart: always
    depends_on:
      - rabbitmq
      - orders-db

  checkout-redis:
    container_name: checkout-redis
    image: bettysami/s5annie-revive-checkout-redis:latest
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - checkout-redis:/data
    networks:   
      - revive
    restart: always

  checkout:
    container_name: checkout
    image: bettysami/s5annie-revive-checkout:latest
    environment:
      REDIS_URL: redis://checkout-redis:6379
      ENDPOINTS_ORDERS: http://orders:8080
    read_only: true
    tmpfs:
    - /tmp:rw,noexec,nosuid
    networks:   
      - revive
    restart: always
    depends_on:
      - orders
      - checkout-redis

  carts-db:
    container_name: carts-db
    image: bettysami/s5annie-revive-carts-db:latest
    environment:
      JAVA_OPTS: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      SERVER_TOMCAT_ACCESSLOG_ENABLED: true
      SPRING_PROFILES_ACTIVE: mysql,rabbitmq
      SPRING_DATASOURCE_WRITER_URL: jdbc:mariadb://orders-db:3306/orders
      SPRING_DATASOURCE_WRITER_USERNAME: orders_user
      SPRING_DATASOURCE_WRITER_PASSWORD: orders1234  # Should match MARIADB_PASSWORD in orders-db
      SPRING_DATASOURCE_READER_URL: jdbc:mariadb://orders-db:3306/orders
      SPRING_DATASOURCE_READER_USERNAME: orders_user
      SPRING_DATASOURCE_READER_PASSWORD: orders1234  # Should match MARIADB_PASSWORD in orders-db
      SPRING_RABBITMQ_HOST: rabbitmq
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - carts-db:/var/lib/mysql
    networks:   
      - revive
    restart: always

  carts:
    container_name: carts
    image: bettysami/s5annie-revive-carts:latest
    environment:
      JAVA_OPTS: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      SERVER_TOMCAT_ACCESSLOG_ENABLED: true
      SPRING_PROFILES_ACTIVE: dynamodb
      CARTS_DYNAMODB_ENDPOINT: http://carts-db:8000
      CARTS_DYNAMODB_CREATETABLE: true
      AWS_ACCESS_KEY_ID: key
      AWS_SECRET_ACCESS_KEY: dummy
    networks:   
      - revive
    restart: always
    depends_on:
      - carts-db

  catalog-db:
    container_name: catalog-db
    image: bettysami/s5annie-revive-catalog-db:latest
    environment:
      MARIADB_ROOT_PASSWORD: orders-db123  # Replace with a secure password
      MARIADB_DATABASE: sampledb
      MARIADB_USER: catalog_user
      MARIADB_PASSWORD: orders1234  # Replace with a secure password
    volumes:
      - catalog-db:/var/lib/mysql
    networks:   
      - revive
    restart: always

  catalog:
    container_name: catalog
    image: bettysami/s5annie-revive-catalog:latest
    environment:
      DB_USER: catalog_user
      DB_HOST: catalog-db
      DB_PASSWORD: orders1234  # Should match MARIADB_PASSWORD in catalog-db
      GIN_MODE: release
    networks:   
      - revive
    restart: always
    depends_on:
      - catalog-db

  assets:
    container_name: assets
    build:
      context: ./assets
          ports:
      - "8082:8080"
    networks:   
      - revive
    restart: always

  ui:
    container_name: ui
    image: bettysami/s5annie-revive-ui:latest
    environment:
      JAVA_OPTS: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      SERVER_TOMCAT_ACCESSLOG_ENABLED: true
      ENDPOINTS_CATALOG: http://catalog:8080
      ENDPOINTS_CARTS: http://carts:8080
      ENDPOINTS_ORDERS: http://orders:8080
      ENDPOINTS_CHECKOUT: http://checkout:8080
      ENDPOINTS_ASSETS: http://assets:8080
    expose:
      - 8080
    ports:
      - 8888:8080     
    networks:   
      - revive
    restart: always
    depends_on:
      - catalog
      - carts
      - orders
      - checkout
      - assets

networks:
  revive:
    driver: bridge

volumes:
  catalog-db:
  orders-db:
  carts-db:
  checkout-redis:
  rabbitmq: