version: '3.0'
services:
  rabbitmq:
    container_name: rabbitmq
    image: 
    environment:
      - name=value
      - name=value
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq:/var/lib/rabbitmq    
    networks:
      - revive
    restart: always
  #  depends_on:    

order-db:
    container_name: order-db
    image: 
    environment:
      - name=value
      - name=value
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq:/var/lib/rabbitmq    
    networks:
      - revive
    restart: always
  #  depends_on: 

