version: '3.0'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - name=value
      - name=value
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq:/var/lib/rabbitmq    
    networks:
      - revive
    restart: always
  #  depends_on:    

orders-db:
    container_name: orders-db
    image: mariadb:10.9
    environment:
      - DB_PASSWORD:
      - DB_USER: orders_user
      - DB_DATABASE: orders
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - orders-dbmariadb-master:/var/lib/rabbitmq:/var/lib/rabbitmq    
    networks:
      - revive
    restart: always
  #  depends_on: 

